# Generated by Django 4.0.2 on 2022-12-09 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_remove_look_category_remove_look_image_look_clothes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='looks/'),
            preserve_default=False,
        ),
    ]
