# Generated by Django 4.0.2 on 2022-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_auctionlistname_bid_category_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
