# Generated by Django 4.0.2 on 2022-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(default='No description for this product', max_length=512),
        ),
    ]
