# Generated by Django 4.0.2 on 2022-03-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(default='No description for this product', max_length=1024),
        ),
    ]
